server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/test/testdb;AUTO_SERVER=TRUE
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

mybatis:
  mapper-locations: mybatis/mapper/**/**.xml
  type-aliases-package: com.isaac.springbootmybatis.mybatis

