server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

mybatis:
  mapper-locations: mybatis/mapper/**/**.xml  # resources path
  type-aliases-package: com.isaac.springbootmybatis.mapper

