server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false # error resolution
    show-sql: true      # show sql
    hibernate:
      ddl-auto: update

  thymeleaf:
    prefix: classpath:/templates/thymeleaf/
    suffix: .html
    check-template-location: true
    cache: false
    mode: HTML
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=true
    username: sa
    password:
